import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import localFont from "next/font/local"
import LAYOUT from "@/commons/layout"
import ApolloHeaderSetting from "@/commons/settings/apollo-settings"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const myLocalFont = localFont({
  src: "./fonts/Pretendard-Regular.woff2",
  variable: "--Pretendard",
})

export const metadata: Metadata = {
  title: "포트폴리오",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko">
      <body className={`${myLocalFont.variable}`}>
        <ApolloHeaderSetting>
          <LAYOUT>{children}</LAYOUT>
        </ApolloHeaderSetting>
      </body>
    </html>
  )
}
